local shared = {
    ButtonInstance = require(script.ButtonInstance),
    ChangeHistoryService = require(script.ChangeHistoryService),
    Clipboard = require(script.Clipboard),
    Config = require(script.Config),
    Icons = require(script.Icons),
    InstanceMap = require(script.InstanceMap),
    PluginButton = require(script.PluginButton),
    PropertyTracker = require(script.PropertyTracker),
    Services = require(script.Services),
    SoundPlayer = require(script.SoundPlayer),
    State = require(script.State),
}
return shared
